#!/usr/bin/env node

const { Client } = require('pg');
let client = new Client({ database: 'expenses'});

async function logQuery(query) {
  await client.connect();
  
  let data = await client.query(query);

  data.rows.forEach(row => {
    let columns = [
      `${row.id}`.padStart(3),
      row.created_on.toDateString().padStart(10),
      row.amount.padStart(12),
      row.memo
    ];

    console.log(columns.join(' | '));
  });

  client.end();
}

logQuery(`
  SELECT * FROM expenses ORDER BY created_on
  `);